
# Data loader
dataset:
  dataset_name: 'Pubmed'
  path: './data/Pubmed/'
  transform: 'NormalizeFeatures'

data_loader:
  loader_type: 'masked_data'

model:
  model_name: 'GCNWalk'
  num_input_features: 500
  num_filters: 16
  num_output_features: 3

trainer:
  trainer_name: 'SimpleMask'
  val_frequency: 1
  number_epoch: 200

  optimizer:
    optimizer_name: 'Adam'
    lr: 0.01
    weight_decay: 1e-5

  loss:
    loss_name: 'nll'
